// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

using System;
using SpacetimeDB;
using ClientApi;
using Newtonsoft.Json.Linq;

namespace StdbCraft.Scripts.SpacetimeDb
{
	public enum ReducerType
	{
		None,
		SendBlockChange,
	}

	public partial class ReducerEvent : ReducerEventBase
	{
		public ReducerType Reducer { get; private set; }

		public ReducerEvent(ReducerType reducer, string reducerName, ulong timestamp, SpacetimeDB.Identity identity, SpacetimeDB.Address? callerAddress, string errMessage, ClientApi.Event.Types.Status status, object args)
			: base(reducerName, timestamp, identity, callerAddress, errMessage, status, args)
		{
			Reducer = reducer;
		}

		public SendBlockChangeArgsStruct SendBlockChangeArgs
		{
			get
			{
				if (Reducer != ReducerType.SendBlockChange) throw new SpacetimeDB.ReducerMismatchException(Reducer.ToString(), "SendBlockChange");
				return (SendBlockChangeArgsStruct)Args;
			}
		}

		public object[] GetArgsAsObjectArray()
		{
			switch (Reducer)
			{
				case ReducerType.SendBlockChange:
				{
					var args = SendBlockChangeArgs;
					return new object[] {
						args.X,
						args.Y,
						args.Z,
						args.BlockId,
					};
				}
				default: throw new System.Exception($"Unhandled reducer case: {Reducer}. Please run SpacetimeDB code generator");
			}
		}
	}
}
